#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := gatt_server_demos

COMPONENT_ADD_INCLUDEDIRS := components/include /home/ellison/libraries/esp32-snippets/cpp_utils 

#EXTRA_COMPONENT_DIRS := /home/ellison/libraries/esp32-snippets/cpp_utils

include $(IDF_PATH)/make/project.mk
